### PR TITLE
Change GeoData to inherit dict so JSON serialization works

### PR DESCRIPTION
**Pull request by jaredfuelberth**

### CODE REVIEW

**Comment by hugorodgerbrown** [comment]
@jaredfuelberth the CI build is currently failing - I think if making serialization simpler is the goal, then using `__dict__` may be a simpler (and non-breaking) change.

```python
>>> foo = GeoData('127.0.0.1')
>>> foo.__dict__
{
  'ip_address': '127.0.0.1',
  'city': None,
  'country_code': None,
  'country_name': None,
  'dma_code': None,
  'latitude': None,
  'longitude': None,
  'postal_code': None,
  'region': None
}
>>> json.dumps(foo)
[traceback]
TypeError: Object of type 'Foo' is not JSON serializable

>>> json.dumps(foo.__dict__)
{
  "ip_address": "127.0.0.1",
  "city": null,
  "country_code": null,
  "country_name": null,
  "dma_code": null,
  "latitude": null,
  "longitude": null,
  "postal_code": null,
  "region": null
}
```

And if you want to make it easy, just add a `serialize` method that will wrap it all up.

```python
>>> foo = GeoData('127.0.0.1')
>>> foo.serialize()
{
  "ip_address": "127.0.0.1",
  "city": null,
  "country_code": null,
  "country_name": null,
  "dma_code": null,
  "latitude": null,
  "longitude": null,
  "postal_code": null,
  "region": null
}
```

That way the existing implementation is unchanged.

**Comment by jaredfuelberth** [comment]
@hugorodgerbrown Yeah I could do that, but the issue was that in lines 86 and 87 in middleware.py; this project passes a GeoData object to the session, and then somewhere inside django.contrib.session it is performing a json.dumps(...) on all the current data, including the GeoData object. At that point, it is not serializable, and it throws the error that I posted in the issues section on this repo. 

Would it be best then to serialize the object to a dict when we pass it into the session, and then deserialize it when we pull it from the session?

**Comment by hugorodgerbrown** [comment]
Yup - I started down a path on this - and having tried to square the serialization circle I ended up asking why I was storing the geodata in session in the first place. It may be that caching the data is more effective - as the geodata is IP bound, not request/user bound, so it has a natural cache key. In which case it can be stored as the object (pickled, not serialized). Would this affect your use of it?

**Comment by hugorodgerbrown** [comment]
@jaredfuelberth I've created a new PR that encompasses this PR (using a dict, not a custom object), but also migrates the implementation over to use the django cache, not session storage.

See #8

**Comment by hugorodgerbrown** [comment]
PR #12 is the update to this PR.

**Pull request closed without merging**
